[cosmic-ray]
module-path = "src/gilded_rose"
python-version = "3.8"
timeout = 5.0
excluded-modules = []
test-command = "pytest"

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.cloning]
method='copy'
commands = []
