import unittest

from gilded_rose import GildedRose, Item


class AcceptanceTests(unittest.TestCase):
    EXPECTED_STATE_BY_DAYS = {
        0: [
            '+5 Dexterity Vest, 10, 20',
            'Aged Brie, 2, 0',
            'Elixir of the Mongoose, 5, 7',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 15, 20',
            'Backstage passes to a TAFKAL80ETC concert, 10, 49',
            'Backstage passes to a TAFKAL80ETC concert, 5, 49',
        ],
        1: [
            '+5 Dexterity Vest, 9, 19',
            'Aged Brie, 1, 1',
            'Elixir of the Mongoose, 4, 6',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 14, 21',
            'Backstage passes to a TAFKAL80ETC concert, 9, 50',
            'Backstage passes to a TAFKAL80ETC concert, 4, 50',
        ],
        2: [
            '+5 Dexterity Vest, 8, 18',
            'Aged Brie, 0, 2',
            'Elixir of the Mongoose, 3, 5',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 13, 22',
            'Backstage passes to a TAFKAL80ETC concert, 8, 50',
            'Backstage passes to a TAFKAL80ETC concert, 3, 50',
        ],
        3: [
            '+5 Dexterity Vest, 7, 17',
            'Aged Brie, -1, 4',
            'Elixir of the Mongoose, 2, 4',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 12, 23',
            'Backstage passes to a TAFKAL80ETC concert, 7, 50',
            'Backstage passes to a TAFKAL80ETC concert, 2, 50',
        ],
        4: [
            '+5 Dexterity Vest, 6, 16',
            'Aged Brie, -2, 6',
            'Elixir of the Mongoose, 1, 3',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 11, 24',
            'Backstage passes to a TAFKAL80ETC concert, 6, 50',
            'Backstage passes to a TAFKAL80ETC concert, 1, 50',
        ],
        5: [
            '+5 Dexterity Vest, 5, 15',
            'Aged Brie, -3, 8',
            'Elixir of the Mongoose, 0, 2',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 10, 25',
            'Backstage passes to a TAFKAL80ETC concert, 5, 50',
            'Backstage passes to a TAFKAL80ETC concert, 0, 50',
        ],
        6: [
            '+5 Dexterity Vest, 4, 14',
            'Aged Brie, -4, 10',
            'Elixir of the Mongoose, -1, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 9, 27',
            'Backstage passes to a TAFKAL80ETC concert, 4, 50',
            'Backstage passes to a TAFKAL80ETC concert, -1, 0',
        ],
        7: [
            '+5 Dexterity Vest, 3, 13',
            'Aged Brie, -5, 12',
            'Elixir of the Mongoose, -2, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 8, 29',
            'Backstage passes to a TAFKAL80ETC concert, 3, 50',
            'Backstage passes to a TAFKAL80ETC concert, -2, 0',
        ],
        8: [
            '+5 Dexterity Vest, 2, 12',
            'Aged Brie, -6, 14',
            'Elixir of the Mongoose, -3, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 7, 31',
            'Backstage passes to a TAFKAL80ETC concert, 2, 50',
            'Backstage passes to a TAFKAL80ETC concert, -3, 0',
        ],
        9: [
            '+5 Dexterity Vest, 1, 11',
            'Aged Brie, -7, 16',
            'Elixir of the Mongoose, -4, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 6, 33',
            'Backstage passes to a TAFKAL80ETC concert, 1, 50',
            'Backstage passes to a TAFKAL80ETC concert, -4, 0',
        ],
        10: [
            '+5 Dexterity Vest, 0, 10',
            'Aged Brie, -8, 18',
            'Elixir of the Mongoose, -5, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 5, 35',
            'Backstage passes to a TAFKAL80ETC concert, 0, 50',
            'Backstage passes to a TAFKAL80ETC concert, -5, 0',
        ],
        11: [
            '+5 Dexterity Vest, -1, 8',
            'Aged Brie, -9, 20',
            'Elixir of the Mongoose, -6, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 4, 38',
            'Backstage passes to a TAFKAL80ETC concert, -1, 0',
            'Backstage passes to a TAFKAL80ETC concert, -6, 0',
        ],
        12: [
            '+5 Dexterity Vest, -2, 6',
            'Aged Brie, -10, 22',
            'Elixir of the Mongoose, -7, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 3, 41',
            'Backstage passes to a TAFKAL80ETC concert, -2, 0',
            'Backstage passes to a TAFKAL80ETC concert, -7, 0',
        ],
        13: [
            '+5 Dexterity Vest, -3, 4',
            'Aged Brie, -11, 24',
            'Elixir of the Mongoose, -8, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 2, 44',
            'Backstage passes to a TAFKAL80ETC concert, -3, 0',
            'Backstage passes to a TAFKAL80ETC concert, -8, 0',
        ],
        14: [
            '+5 Dexterity Vest, -4, 2',
            'Aged Brie, -12, 26',
            'Elixir of the Mongoose, -9, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 1, 47',
            'Backstage passes to a TAFKAL80ETC concert, -4, 0',
            'Backstage passes to a TAFKAL80ETC concert, -9, 0',
        ],
        15: [
            '+5 Dexterity Vest, -5, 0',
            'Aged Brie, -13, 28',
            'Elixir of the Mongoose, -10, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, 0, 50',
            'Backstage passes to a TAFKAL80ETC concert, -5, 0',
            'Backstage passes to a TAFKAL80ETC concert, -10, 0',
        ],
        16: [
            '+5 Dexterity Vest, -6, 0',
            'Aged Brie, -14, 30',
            'Elixir of the Mongoose, -11, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, -1, 0',
            'Backstage passes to a TAFKAL80ETC concert, -6, 0',
            'Backstage passes to a TAFKAL80ETC concert, -11, 0',
        ],
        17: [
            '+5 Dexterity Vest, -7, 0',
            'Aged Brie, -15, 32',
            'Elixir of the Mongoose, -12, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, -2, 0',
            'Backstage passes to a TAFKAL80ETC concert, -7, 0',
            'Backstage passes to a TAFKAL80ETC concert, -12, 0',
        ],
        18: [
            '+5 Dexterity Vest, -8, 0',
            'Aged Brie, -16, 34',
            'Elixir of the Mongoose, -13, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, -3, 0',
            'Backstage passes to a TAFKAL80ETC concert, -8, 0',
            'Backstage passes to a TAFKAL80ETC concert, -13, 0',
        ],
        19: [
            '+5 Dexterity Vest, -9, 0',
            'Aged Brie, -17, 36',
            'Elixir of the Mongoose, -14, 0',
            'Sulfuras, Hand of Ragnaros, 0, 80',
            'Sulfuras, Hand of Ragnaros, -1, 80',
            'Backstage passes to a TAFKAL80ETC concert, -4, 0',
            'Backstage passes to a TAFKAL80ETC concert, -9, 0',
            'Backstage passes to a TAFKAL80ETC concert, -14, 0',
        ],
    }

    def setUp(self) -> None:
        self.items = [
            Item(name="+5 Dexterity Vest", sell_in=10, quality=20),
            Item(name="Aged Brie", sell_in=2, quality=0),
            Item(name="Elixir of the Mongoose", sell_in=5, quality=7),
            Item(name="Sulfuras, Hand of Ragnaros", sell_in=0, quality=80),
            Item(name="Sulfuras, Hand of Ragnaros", sell_in=-1, quality=80),
            Item(
                name="Backstage passes to a TAFKAL80ETC concert",
                sell_in=15,
                quality=20
            ),
            Item(
                name="Backstage passes to a TAFKAL80ETC concert",
                sell_in=10,
                quality=49,
            ),
            Item(
                name="Backstage passes to a TAFKAL80ETC concert",
                sell_in=5,
                quality=49,
            ),
        ]
        self.gilded_rose = GildedRose(self.items)

    def test_verify_results_by_days(self):
        for day in range(20):
            day_results = self.EXPECTED_STATE_BY_DAYS[day]
            for i, item in enumerate(self.items):
                expected = day_results[i]
                with self.subTest(day=day, item=item, expected=expected):
                    self.assertEqual(str(item), expected)
            self.gilded_rose.update_quality()
